### ISSUE TITLE
show time not only date

### ISSUE THREAD

**Issue by hpvd** [piwik/plugin-TasksTimetable#7]
would be handy to see also time not only day and date
please see attachment
![2016-01-28_08h45_08](https://cloud.githubusercontent.com/assets/5681880/12638310/65f279bc-c59c-11e5-91f9-c618a8fb0609.png)

**Comment by mattab** [comment]
Thank for suggestion I also needed this, fixed in https://github.com/piwik/plugin-TasksTimetable/commit/f37380f1e650698a5dd660bf766458ec9fbaa2b8 and will be released in 0.2.2

**Comment by hpvd** [comment]
thankyou!
